### ISSUE TITLE
configuration help aadpodidbinding, in deployment/statefullset

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/gatekeeper-library#43]
Recently I did a stupid error that was to label the deployment with: aadpodidbinding instead of the pod template.
Let's create a warning that tells the user that you shouldn't do that :)

**Bellow is not okay**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aadpodidbinding: backend
  name: podinfo
spec:

```

**This one is okay**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    metadata:
      labels:
        aadpodidbinding: backend
        app: podinfo
```
