### ISSUE TITLE
drop-net-raw don't understand ALL

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/gatekeeper-library#48]
Even if below config is defined our current mutations complain about missing `RAW_NET`
 
```
securityContext:
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
```

as defined in: https://github.com/XenitAB/gatekeeper-library/blob/971eb83b643b965b74f84c5843672fb32fbf8e49/library/assigns/container-drop-net-raw.yaml

Since ALL is more then NET_RAW it shouldn't complain about this.

This is not a big issue but enjoying :)
